#!/bin/bash

xsetroot -cursor_name left_ptr
setxkbmap -option altwin:swap_alt_win
wmname LG3D

sxhkd &

bspc monitor 				-d 1 2 3 4 5 6 7 8 9 10

bscp config remove_disabled_monitors	true
bspc config remove_unplugged_monitors	true
bspc config pointer_follows_monitor	true
bspc config merge_overlapping_monitors	true
bspc config history_aware_focus 	true

bspc config active_border_color 	'#0C1115'
bspc config normal_border_color 	'#0C1115'
bspc config focused_border_color 	'#86ddff'

bspc config top_padding			25
bspc config bottom_padding		0
bspc config right_padding		0
bspc config left_padding		0

bspc config border_width		1
bspc config window_gap			1

bspc config split_ratio          	0.50
bspc config borderless_monocle   	true
# bspc config gapless_monocle      	true
bspc config single_monocle		true

bspc config pointer_modifier 		mod1
bspc config pointer_action1  		move
bspc config pointer_action2  		resize_side
bspc config pointer_action3  		resize_corner

